CoreCourse.Efbasics.Web/Controllers/CartController.cs
using CoreCourse.Efbasics.Web.Data;
using CoreCourse.Efbasics.Web.Models;
using CoreCourse.Efbasics.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace CoreCourse.Efbasics.Web.Controllers
{
    public class CartController : Controller
    {
        private readonly SchoolDbContext _schoolDbContext;

        public CartController(SchoolDbContext schoolDbContext)
        {
            _schoolDbContext = schoolDbContext;
        }

        public IActionResult Index()
        {
            CartIndexViewModel cartIndexViewModel = new();
            cartIndexViewModel.Items = new();
            //check if session exists
            //and get the data from the sessio
            if (HttpContext.Session.Keys.Contains("ShoppingCart"))
            {
                //get the serialized viewmodel from the session
                var serializedCartIndexViewModel = HttpContext
                    .Session.GetString("ShoppingCart");
                cartIndexViewModel =
                    JsonConvert
                    .DeserializeObject<CartIndexViewModel>(serializedCartIndexViewModel);
            }
            //calculate total
            cartIndexViewModel.Total = cartIndexViewModel.Items
                .Sum(i => i.Price);
            //pass to view
            return View(cartIndexViewModel);
        }
        public async Task<IActionResult> Add(int id) 
        {
            //get the course and check if exists
            var course = await _schoolDbContext
                .Courses
                .FirstOrDefaultAsync(c => c.Id == id);
            if (course == null)
            {
                return RedirectToAction("Index","Courses");
            }
            //course exists
            CartIndexViewModel cartIndexViewModel = new();
            cartIndexViewModel.Items = new();
            string serializedCartIndexViewModel = "";
            //check if session exists
            if(HttpContext.Session.Keys.Contains("ShoppingCart"))
            {
                //get the serialized viewmodel from the session
                serializedCartIndexViewModel = HttpContext
                    .Session.GetString("ShoppingCart");
                cartIndexViewModel =
                    JsonConvert
                    .DeserializeObject<CartIndexViewModel>(serializedCartIndexViewModel);
            }

            //add product to viewmodel list
            //check if item already in shoppingCart
            if(cartIndexViewModel.Items.Any(c => c.Id == course.Id)) 
            {
                //increment quantity 
                var item = cartIndexViewModel
                    .Items
                    .FirstOrDefault(i => i.Id == course.Id);
                item.Quantity++;
                item.Price += course.Price;
            }
            else
            {
                //add new item
                cartIndexViewModel.Items
                .Add(new CartItemViewModel
                {
                    Id = course.Id,
                    Name = course.Name,
                    Quantity = 1,
                    Price = course.Price
                }
                );
            }
            //serialize viewmodel
            serializedCartIndexViewModel = 
                JsonConvert.SerializeObject( cartIndexViewModel );
            //add to session => overwrite session with new shoppingCart
            HttpContext.Session.SetString("ShoppingCart", serializedCartIndexViewModel);
            //update counter
            HttpContext.Session.SetInt32("CartCounter", cartIndexViewModel
                .Items.Sum(i => i.Quantity));
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Remove(int id) 
        {
            //check if course exists
            //get the course and check if exists
            //may be redundant check
            var course = await _schoolDbContext
                .Courses
                .FirstOrDefaultAsync(c => c.Id == id);
            if (course == null)
            {
                return RedirectToAction("Index", "Courses");
            }
            //course exists
            CartIndexViewModel cartIndexViewModel = new();
            cartIndexViewModel.Items = new();
            string serializedCartIndexViewModel = "";
            //check if session exists
            if (!HttpContext.Session.Keys.Contains("ShoppingCart"))
            {
                return RedirectToAction("Index", "Courses");
            }
            //get the serialized viewmodel from the session
            serializedCartIndexViewModel = HttpContext
                .Session.GetString("ShoppingCart");
            cartIndexViewModel =
                JsonConvert
                .DeserializeObject<CartIndexViewModel>(serializedCartIndexViewModel);
            //get the item
            var item = cartIndexViewModel.Items.FirstOrDefault(i => i.Id == id);
            //check if exists in shoppingCart
            if(item == null ) 
            {
                RedirectToAction("Index", "Courses");
            }
            //remove item
            //check for quantity
            if(item.Quantity > 1)
            {
                item.Quantity--;
                item.Price = (course.Price * item.Quantity);
            }
            else
            {
                //remove from list
                cartIndexViewModel.Items.Remove(item);
            }
            //update session
            //serialize viewmodel
            serializedCartIndexViewModel =
                JsonConvert.SerializeObject(cartIndexViewModel);
            //add to session => overwrite session with new shoppingCart
            HttpContext.Session.SetString("ShoppingCart", serializedCartIndexViewModel);
            //update counter
            HttpContext.Session.SetInt32("CartCounter", cartIndexViewModel
                .Items.Sum(i => i.Quantity));
            return RedirectToAction("Index");
        }
    }
}

CoreCourse.Efbasics.Web/Controllers/StudentsController.cs
using CoreCourse.Efbasics.Web.Data;
using CoreCourse.Efbasics.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CoreCourse.Efbasics.Web.Controllers
{
    public class StudentsController : Controller
    {
        private readonly SchoolDbContext _schoolDbContext;

        public StudentsController(SchoolDbContext schoolDbContext)
        {
            _schoolDbContext = schoolDbContext;
        }

        public IActionResult Index()
        {
            var studentsIndexViewModel = new StudentsIndexViewModel
            {
                Students = _schoolDbContext.Students
                .Select(s => new BaseViewModel
                {
                    Id = s.Id,
                    Name = $"{s.Firstname} {s.Lastname}"
                })
            };
            return View(studentsIndexViewModel);
        }
    }
}

CoreCourse.Efbasics.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreCourse.Efbasics.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CoreCourse.Efbasics.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoreCourse.Efbasics.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Admin"
                               asp-action="Index">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cart"
                               asp-action="Index">
                                @* check if CartCounter session exists *@
                                @if(Context.Session.Keys.Contains("CartCounter"))
                                {
                                    <span class="icon-shopping-cart"></span> <b>@Context.Session.GetInt32("CartCounter")</b>
                                }
                                else
                                { 
                                    <span class="icon-shopping-cart"></span><b> 0</b>
                                }
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CoreCourse.Efbasics.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>