CoreCourse.Efbasics.Web/Areas/Admin/Controllers/CoursesController.cs
using CoreCourse.Efbasics.Core.Entities;
using CoreCourse.Efbasics.Web.Areas.Admin.ViewModels;
using CoreCourse.Efbasics.Web.Data;
using CoreCourse.Efbasics.Web.Services;
using CoreCourse.Efbasics.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Immutable;
using System.Data.Common;

namespace CoreCourse.Efbasics.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CoursesController : Controller
    {
        private readonly SchoolDbContext _schoolDbContext;
        private readonly IFormBuilderService _formBuilderService;

        public CoursesController(SchoolDbContext schoolDbContext, IFormBuilderService formBuilderService)
        {
            _schoolDbContext = schoolDbContext;
            _formBuilderService = formBuilderService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var coursesIndexViewModel = new CoursesIndexViewModel();
            coursesIndexViewModel.Courses = await _schoolDbContext
                .Courses
                .Select(c => new CoursesDetailViewModel
                {
                    Id = c.Id,
                    Name = c.Name,
                    Teacher = new BaseViewModel
                    {
                        Id = c.TeacherId,
                        Name = $"{c.Teacher.Firstname} {c.Teacher.Lastname}",
                    }
                }).ToListAsync(); ;
            return View(coursesIndexViewModel);
        }
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            //create viewmodel
            var coursesAddViewModel = new CoursesAddViewModel();
            //get the teachers from database
            var teachers = await _schoolDbContext
                .Teachers
                .OrderBy(t => t.Lastname)
                .ToListAsync();
            //put in list
            coursesAddViewModel.Teachers
                = await _formBuilderService.BuildTeacherDropDown();
            //pass to the view
            ViewBag.PageTitle = "Add a course";
            return View(coursesAddViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(CoursesAddViewModel coursesAddViewModel)
        {
            //check if course exists
            //use custom model error
            //remove whitespaces
            if(await _schoolDbContext.Courses
                .FirstOrDefaultAsync(c => c.Name.ToUpper().Replace(" ","") == coursesAddViewModel.Name.ToUpper().Replace(" ","")) != null)
            {
                //add model error
                ModelState.AddModelError("Name", "Course already exists!");
            }
            if (!ModelState.IsValid)
            {
                ViewBag.PageTitle = "Add a course";
                coursesAddViewModel.Teachers
                    = await _formBuilderService.BuildTeacherDropDown();
                return View(coursesAddViewModel);
            }
            //create the new course
            var course = new Course();
            //trim whites
            course.Name= coursesAddViewModel.Name.Trim();
            course.TeacherId = coursesAddViewModel.TeacherId;
            //add to the tracking context
            await _schoolDbContext.Courses.AddAsync(course);
            //save to the database
            try 
            {
                await _schoolDbContext.SaveChangesAsync();
            }
            catch(DbException dbException)
            {
                Console.WriteLine(dbException.Message);
            }
            return RedirectToAction("Index");
        }
    }
}

CoreCourse.Efbasics.Web/Areas/Admin/Controllers/TeachersController.cs
using CoreCourse.Efbasics.Web.Data;
using Microsoft.AspNetCore.Mvc;

namespace CoreCourse.Efbasics.Web.Areas.Admin.Controllers
{
    public class TeachersController : Controller
    {
        private readonly SchoolDbContext _schoolDbContext;

        public TeachersController(SchoolDbContext schoolDbContext)
        {
            _schoolDbContext = schoolDbContext;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

CoreCourse.Efbasics.Web/Controllers/CoursesController.cs
using CoreCourse.Efbasics.Core.Entities;
using CoreCourse.Efbasics.Web.Data;
using CoreCourse.Efbasics.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CoreCourse.Efbasics.Web.Controllers
{
    public class CoursesController : Controller
    {
        //declare Db context
        private readonly SchoolDbContext _schoolDbContext;

        public CoursesController(SchoolDbContext schoolDbContext)
        {
            //dependency injection
            _schoolDbContext = schoolDbContext;
        }

        public IActionResult Index()
        {
            //show a list of courses
            //get the courses
            var courses = _schoolDbContext
                .Courses
                .Include(c => c.Students)
                .Include(c => c.Teacher);
            //viewmodel
            CoursesIndexViewModel coursesIndexViewModel
                = new CoursesIndexViewModel();
            //fill the model
            coursesIndexViewModel.Courses
                = courses.Select(c => new CoursesDetailViewModel
                {
                    Id = c.Id,
                    Name = c.Name,
                    Teacher = new BaseViewModel
                    {
                        Id = c.Teacher.Id,
                        Name = $"{c.Teacher.Firstname} {c.Teacher.Lastname}"
                    },
                    Price= c.Price,
                });
            return View(coursesIndexViewModel);

        }
    }
}

CoreCourse.Efbasics.Web/Areas/Admin/Views/Courses/Add.cshtml
@model CoursesAddViewModel

<div class="row">
    <div class="col col-lg-4 mx-auto">
        <h2>@ViewBag.PageTitle</h2>
        <form asp-area="Admin" asp-controller="Courses" asp-action="Add" method="post">
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            @* dropdown with teachers *@
            <div class="form-group">
                <label asp-for="TeacherId"></label>
                <select asp-for="TeacherId" asp-items="@Model.Teachers" class="form-select"></select>
                </div>
            <button type="submit" class="btn btn-primary">Add</button>
        </form>
        <a asp-area="Admin" asp-controller="Courses" asp-action="Index"
           class="btn btn-info mt-2 mb-2">Back</a>
    </div>
</div>

CoreCourse.Efbasics.Web/Areas/Admin/Views/Courses/Index.cshtml
@model CoursesIndexViewModel
<div class="row">
    <div class="col col-lg-4 mx-auto">
        <h2>Our courses</h2>
        <a asp-area="Admin" asp-controller="Courses" asp-action="Add"
           class="btn btn-outline-info">New course</a>
        <table class="table table-hover table-responsive-lg">
            <tr>
                <th>Name</th>
                <th>Teacher</th>
                <th>Action</th>
            </tr>
            @foreach (var course in Model.Courses)
            {
                <tr>
                    <td>@course.Name</td>
                    <td><a asp-area="Admin"
                           asp-controller="Teachers"
                           asp-action="Update"
                           asp-route-id="@course.Teacher.Id" class="link-info">@course.Teacher.Name</a></td>
                    <td>
                        <a asp-area="Admin"
                           asp-controller="courses"
                           asp-action="Update"
                           asp-route-id="@course.Id" class="btn btn-outline-info">
                            Edit
                        </a>
                    </td>
                    <td>
                        <a asp-area="Admin"
                           asp-controller="courses"
                           asp-action="ConfirmDelete"
                           asp-route-id="@course.Id" class="btn btn-outline-danger">
                            Delete
                        </a>
                    </td>
                </tr>
            }
        </table>

    </div>
</div>